### ISSUE TITLE
"Style property zIndex is not supported by native animated module" while using circular progress bar

### ISSUE THREAD

**Issue by mohammedavez** [iamshadmirza/react-native-design-system#12]

**Comment by iamshadmirza** [comment]
Can you share your code?  
How you're using it.

**Comment by volKate** [comment]
@iamshadmirza I got the same error. Elevation is only supported for android, so on iOS third circle covers the first one, when percent > 50. Adding zIndex: elevation3 causes "Style property zIndex is not supported by native animated module", because it is a layout property

**Comment by MonkeyThunk** [comment]
I had to set useNativeDriver to false to workaround that

**Comment by iamshadmirza** [comment]
commit b66349e fixes this issue
Thanks for help @MonkeyThunk
