### ISSUE TITLE
"Animated node with tag 13 does not exists"

### ISSUE THREAD

**Issue by mohammedavez** [iamshadmirza/react-native-design-system#13]
While using circular progress bar I am getting the error "Animated node with tag 13 does not exists"

**Comment by iamshadmirza** [comment]
Hey @mohammedavez 
I know I'm pretty late but can you please tell me which platform you're using
Android or iOS?

**Comment by iamshadmirza** [comment]
I'm unable to recreate the issue. Closing this for now due to inactivity. Feel free to reopen.
