### ISSUE TITLE
Typing is wrong for Input's onChangeText.

### ISSUE THREAD

**Issue by gablabelle** [iamshadmirza/react-native-design-system#15]
Hello,

FYI, `value` is optional (it works without it being set), typing should be `value?: string`

https://github.com/iamshadmirza/react-native-design-system/blob/8f8a8ae603b1967d6f4e10d8302265bae4fa7fe2/src/types/Input.d.ts#L13

and `onChangeText` is missing the text it's returning, typing should be `onChangeText: (text: string) => void,`

https://github.com/iamshadmirza/react-native-design-system/blob/8f8a8ae603b1967d6f4e10d8302265bae4fa7fe2/src/types/Input.d.ts#L14

**Comment by iamshadmirza** [comment]
Fixed
