### ISSUE TITLE
Example of textStyle for MenuAddButton

### ISSUE THREAD

**Issue by in2progress** [iamshadmirza/react-native-design-system#18]
Hi,

I am trialling out your framework and have tried to set the inner style of the the MenuAddButton Component.

Example as per below: 
<MenuAddButton style={{backgroundColor:'green', borderRadius:20}} textStyle={{backgroundColor:'white'}} onIncrement={handleIncrement} onDecrement={handleDecrement} count={count} />

The background colour remains grey after incrementing.

Please assist.

**Comment by iamshadmirza** [comment]
Will create a demo and add it. Give me a day.

**Comment by iamshadmirza** [comment]
Hey @in2progress 
This is fixed. Please install the latest version `1.2.1`
Thanks for reporting.

**Comment by in2progress** [comment]
Hi,

Unfortunately failing with different error now. 

Before clicking.
<img width="160" alt="image" src="https://user-images.githubusercontent.com/11703991/92721902-b5c0ac80-f35e-11ea-99c5-21ad9133f73f.png">

After clicking
<img width="223" alt="image" src="https://user-images.githubusercontent.com/11703991/92721990-d38e1180-f35e-11ea-9a5e-fde7cb5cbedc.png">

Same code: <MenuAddButton style={{backgroundColor:'green', borderRadius:20}} textStyle={{backgroundColor:'white'}} onIncrement={handleIncrement} onDecrement={handleDecrement} count={count} />

Fails with same error without textStyle attribute.

RN: 0.63
iOS: Simulator 13.6

**Comment by iamshadmirza** [comment]
Damn
Reopening this issue
Sent a fix. Can you please confirm and close this issue if it works?

**Comment by in2progress** [comment]
That worked. Thank you!
