### ISSUE TITLE
CircularProgressBar

### ISSUE THREAD

**Issue by in2progress** [iamshadmirza/react-native-design-system#20]
Tried direct from Usage page for CircularProgressBar. In Simulator and Device the bar is distorted. rn-063, Simulator and Device on iOS 13.6

<img width="171" alt="image" src="https://user-images.githubusercontent.com/11703991/92580496-58f1c300-f286-11ea-9b1e-eaf8991dc618.png">

<CircularProgressBar
    activeColor="darkviolet"
    passiveColor="darkgrey"
    baseColor="white"
    width={50}
    percent={35}
    radius={100}
    duration={1200}
  >

**Comment by iamshadmirza** [comment]
Hey there, I just tested this on iOS and it does have this issue. Please give me some time. I'll fix the bug and update library.

**Comment by iamshadmirza** [comment]
Hey @in2progress 
This is fixed. Please install the latest version `1.2.1`
Thanks for reporting.
