### ISSUE TITLE
SearchBar issue

### ISSUE THREAD

**Issue by in2progress** [iamshadmirza/react-native-design-system#21]
:) Sorry, another one. 

RN: 0.63
OS: Simulator 13.6

`<Stack>
<SearchBar outline placeholder="Search for location" leftIcon={<FontAwesome5 name="user" size={22} color="grey" />} value="" onChangeText={text => {console.log(text)}} />
</Stack>`

<img width="340" alt="image" src="https://user-images.githubusercontent.com/11703991/92745692-7d2ecc00-f37a-11ea-8077-a159b8a28f67.png">

**Comment by iamshadmirza** [comment]
Thanks for reporting.
Will fix this too.

**Comment by iamshadmirza** [comment]
Fixed @in2progress 
I wanted to ask if you can help me fix the library and make it better. You can just keep reporting whatever error you're facing and I'll fix those.
